#! /bin/bash

FTEMP="/etc/portage/package."

print_help() {
    cat <<EOF
This is the help message for my quickly written script

Options:
    -a|--accept-keywords
        Add a proceeding string to the package.accept_keywords file
    -u|--use
        Add a proceeding string to the package.use file
    -um|--unmask
        Add a proceeding string to the package.unmask file
    -m|--mask
        Add a proceeding string to the package.mask file

Example:
    metool -a "sys-kernel/gentoo-sources ~amd64"
EOF
}

case $1 in
    -a|--accept-keywords)
        FILE="${FTEMP}accept_keywords"
        shift
        ;;
    -u|--use)
        FILE="${FTEMP}use"
        shift
        ;;
    -um|--unmask)
        FILE="${FTEMP}unmask"
        shift
        ;;
    -m|--mask)
        FILE="${FTEMP}mask"
        shift
        ;;
    -h|--help|*)
        print_help
        exit 0
        ;;
esac

if [[ $UID != 0 ]]; then
    echo "$@" | sudo tee -a $FILE
else
    echo "$@" >> $FILE
fi
echo "Done"
exit 0
