#!/bin/sh 

startup()
{
  if ps -A | grep -q $1; then
    echo "$1 is already running"
  else
    `$@` &
    notify-send "$1"
  fi
}

# Keyboard
setxkbmap gb
xset +dpms 

# Start misc stuff
#startup "xbindkeys"
#startup "wpa_gui" "-t"
#startup "thunderbird-bin"
