# Auto-generated by canto because you don't have one.
# Please copy to/create ~/.canto/conf.py

add("http://git.naquadah.org/?p=awesome.git;a=atom")
add("http://feeds.feedburner.com/Phoronix")
add("http://planet.archlinux.org/atom.xml")
add("http://rss.slashdot.org/slashdot/Slashdot")
add("http://xkcd.com/atom.xml")
add("http://codezen.org/canto/feeds/latest")

link_handler("firefox \"%u\"")

#reader_orientation = "left"

#def resize_hook(cfg):
#   cfg.reader_orientation = "left"
#   cfg.reader_lines = cfg.width / 2
#   cfg.columns = (cfg.width / 2) / 65

from canto.extra import *

filters=[show_unread, None]
